version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: shop_acc_game_db
    environment:
      POSTGRES_DB: shop_acc_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # POSTGRES_HOST_AUTH_METHOD: trust
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shop_acc_game_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopaccgame.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
