version: '3.8' 
services: 
  postgres: 
    image: postgres:14-alpine
    container_name: shop_acc_game_postgres 
    environment: 
      POSTGRES_DB: shop_acc_game 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: shopaccgame2024! 
    ports: 
      - "5432:5432" 
    volumes: 
      - postgres_data:/var/lib/postgresql/data 
    restart: unless-stopped 
volumes: 
  postgres_data: 
