version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: shop_acc_game_db
    environment:
      POSTGRES_DB: shop_acc_game
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # POSTGRES_HOST_AUTH_METHOD: trust
      
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: shop_acc_game_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@shopaccgame.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shop_acc_game_backend
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/shop_acc_game
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - JWT_SECRET=your-super-secret-jwt-key-here-make-it-long-and-secure
      - MAIL_USERNAME=gurroshop@gmail.com
      - MAIL_PASSWORD=ijhfgedfazirgdrx
      - RAWG_API_KEY=5901cb0625a547eb922e9c700744032e
      - GOOGLE_CLIENT_ID=915027856276-41dpec5j8s73178jkiojn5nd15pb5sh5.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - DB_READINESS_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shop_acc_game_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  backend_uploads:

networks:
  app-network:
    driver: bridge
